project:
  type: book

book:
  title: "AUEHPRC_PolicyandProcedures"
  author: "Norah Jones"
  date: "12/2/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - easley.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



